### ISSUE TITLE
new comments modal ui 

### ISSUE THREAD

**Issue by erica-zhong** [WycliffeAssociates/translationExchange#211]
- [x] Loading indication when saving a comment
- [x] error message if comment doesn't save (this is annoying because you have to record a new comment, maybe make it save the comment you have recorded, and just have to press save again)
- [x] warning when deleting a comment
- [x] weird blue inner circle on stop button
- [x] only half of both buttons are clickable??? SO WEIRD (just kidding this was a me problem)
- [x] error message for trying to delete a comment that just was deleted by someone else
- is it intuitive that pressing record again will record a new button or should there be a cancel button?

**Comment by Redmayspecial** [comment]
Closed due to design changes
