### ISSUE TITLE
Remember User Accounts

### ISSUE THREAD

**Issue by nathanalbers** [WycliffeAssociates/translationExchange#31]
## User Story
As a translator, I want my name to be remembered and offered an option to choose when I identify myself so I don't have to keep retyping my identity. 

## Acceptance Criteria
- [ ] You are able to select from previously entered names when you log in

## Tasks
- [ ] When the user is logging in, UI for displaying and choosing a previously entered name

**Comment by Redmayspecial** [comment]
Closed due to design changes
